# Generated by Django 4.2.5 on 2023-09-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs/'),
        ),
    ]
